---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 1h
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.10@sha256:e7ae47ca41254acea24612da3b7516c413f54fe5eee43728355a8a2b75953a8c
            env:
              TZ: America/Los_Angeles
              # TODO: Move to proper setup. This mimics the linuxserver image
              JELLYFIN_DATA_DIR: /config/data
              JELLYFIN_CONFIG_DIR: /config
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 8Gi
            securityContext:
              privileged: true # Needed for hardware acceleration
    service:
      app:
        annotations:
          lbipam.cilium.io/ips: 192.168.2.7
        externalTrafficPolicy: Local
        ports:
          http:
            port: *port
            appProtocol: kubernetes.io/ws
        type: LoadBalancer
    route:
      app:
        hostnames:
        - "{{ .Release.Name }}.brenix.com"
        parentRefs:
        - name: envoy-external
          namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}-data"
      cache:
        existingClaim: "{{ .Release.Name }}-cache"
        globalMounts:
        - path: /config/cache
      media:
        type: nfs
        server: trinity.home.arpa
        path: /mnt/main/media
        globalMounts:
        - path: /media
      transcode:
        type: emptyDir
      dri:
        type: hostPath
        hostPathType: Directory
        hostPath: /dev/dri
