---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  chartRef:
    kind: OCIRepository
    name: sabnzbd
  interval: 1h
  values:
    controllers:
      sabnzbd:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 5.0.3@sha256:53064020792b2e21305c892c11aaa1eb32af2141cbd59119b52df226d664cd05
            env:
              TZ: America/Los_Angeles
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                cpu: 2
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
        strategy: Recreate
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames:
        - "{{ .Release.Name }}.brenix.com"
        parentRefs:
        - name: envoy-internal
          namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      downloads:
        type: nfs
        server: trinity.home.arpa
        path: /mnt/main/media/downloads
        globalMounts:
        - path: /downloads/complete
          subPath: complete
      incomplete:
        type: emptyDir
        globalMounts:
        - path: /downloads/incomplete
      tmp:
        type: emptyDir
