---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: prowlarr
    template:
      data:
        PROWLARR__AUTH__APIKEY: "{{ .PROWLARR_API_KEY }}"
  data:
  - secretKey: &key PROWLARR_API_KEY
    remoteRef:
      key: *key
