---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-minio-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: velero-minio-credentials
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .VELERO_MINIO_ACCESS_KEY_ID }}
          aws_secret_access_key={{ .VELERO_MINIO_SECRET_ACCESS_KEY }}
  data:
  - secretKey: VELERO_MINIO_ACCESS_KEY_ID
    remoteRef:
      key: VELERO_MINIO_ACCESS_KEY_ID
  - secretKey: VELERO_MINIO_SECRET_ACCESS_KEY
    remoteRef:
      key: VELERO_MINIO_SECRET_ACCESS_KEY
