---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  chartRef:
    kind: OCIRepository
    name: velero
  interval: 1h
  values:
    image:
      repository: velero/velero
      tag: v1.18.0@sha256:e4d1e79be2ee1d51056734ada5e51c78a29b924e4d055cd28e0b4103ae2268ad
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.13.2
      volumeMounts:
      - mountPath: /target
        name: plugins
    upgradeCRDs: false
    kubectl:
      image:
        repository: docker.io/alpine/kubectl
        tag: 1.35.2
    metrics:
      serviceMonitor:
        enabled: true
      nodeAgentPodMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    configuration:
      features: EnableCSI
      backupStorageLocation:
      - name: default
        provider: aws
        bucket: velero
        config:
          region: us-east-1
          s3Url: http://192.168.1.15:9000
          s3ForcePathStyle: true
      logLevel: info # warning
      extraEnvVars:
      - name: TZ
        value: America/Los_Angeles
      defaultVolumesToFsBackup: false
      volumeSnapshotLocation:
      - name: default
        provider: aws
        config:
          region: us-east-1
    credentials:
      existingSecret: velero-minio-credentials
    backupsEnabled: true
    snapshotsEnabled: true
    deployNodeAgent: true
    schedules:
      default:
        schedule: '0 0 */3 * *'
        template:
          excludedResources:
          - challenges.acme.cert-manager.io
          - orders.acme.cert-manager.io
          - certificaterequests.cert-manager.io
          - ciliumendpoints.cilium.io
          - endpoints
          - endpointslices
          - helmcharts.source.toolkit.fluxcd.io
          - helmreleases.helm.toolkit.fluxcd.io
          - helmrepositories.source.toolkit.fluxcd.io
          - kustomizations.kustomize.toolkit.fluxcd.io
          - ocirepositories.source.toolkit.fluxcd.io
          includedNamespaces:
          - '*'
          ttl: 150h0m0s
          snapshotMoveData: true
          snapshotVolumes: true
