[env]
DIFF= "dyff between --omit-header --color on"
DOPPLER_CONFIG = "main"
DOPPLER_PROJECT = "home-ops"
JUST_UNSTABLE = "1"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
SOPS_AGE_KEY_FILE = "{{config_root}}/.private/age.key"
TALOSCONFIG = "{{config_root}}/talosconfig"

[tools]
age = "1.3"
cilium-cli = "0.19"
dyff = "latest"
flux2 = "2.9.3"
"github:mitsuhiko/minijinja" = "2.23.0"
gum = "0.17"
helm = "4"
helmfile = "1.7.3"
just = "1.58.0"
kubeconform = "0.8.0"
sops = "3.13.3"
stern = "1.34.0"
talos = "1.13.8"
task = "3.52.0"
velero = "1.18"
yamlfmt = "0.21"
yq = "4.53"
"github:home-operations/flate" = "latest"
