---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: konflate-webhook-token-secret
    template:
      data:
        KONFLATE_WEBHOOK_SECRET: "{{ .KONFLATE_WEBHOOK_SECRET }}"
  data:
    - secretKey: &key KONFLATE_WEBHOOK_SECRET
      remoteRef:
        key: *key
