---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: linkding
    template:
      data:
        LD_SUPERUSER_NAME: "{{ .LINKDING_USER }}"
        LD_SUPERUSER_PASSWORD: "{{ .LINKDING_PASS }}"
  data:
  - secretKey: &userKey LINKDING_USER
    remoteRef:
      key: *userKey
  - secretKey: &passKey LINKDING_PASS
    remoteRef:
      key: *passKey

