---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkding
spec:
  chartRef:
    kind: OCIRepository
    name: linkding
  interval: 1h
  values:
    controllers:
      linkding:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/sissbruecker/linkding
              tag: 1.46.2@sha256:0c0a9a04c7ebd644293c37f98710872fe7cdff0ea1ff7fd9be4d235e4c4678d2
            envFrom:
            - secretRef:
                name: "{{ .Release.Name }}"
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 512Mi
        strategy: Recreate
    service:
      app:
        ports:
          http:
            port: 9090
    route:
      app:
        hostnames:
        - "{{ .Release.Name }}.brenix.com"
        parentRefs:
        - name: envoy-internal
          namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}-data"
        globalMounts:
        - path: /etc/linkding/data
