---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: github-webhook-token-secret
    template:
      data:
        token: "{{ .FLUX_WEBHOOK_TOKEN }}"
  data:
  - secretKey: &key FLUX_WEBHOOK_TOKEN
    remoteRef:
      key: *key
