---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stirling-pdf
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: stirling-pdf
    template:
      data:
        SECURITY_INITIALLOGIN_USERNAME: "{{ .STIRLING_PDF_ADMIN_USERNAME }}"
        SECURITY_INITIALLOGIN_PASSWORD: "{{ .STIRLING_PDF_ADMIN_PASSWORD }}"
  data:
  - secretKey: STIRLING_PDF_ADMIN_USERNAME
    remoteRef:
      key: STIRLING_PDF_ADMIN_USERNAME
  - secretKey: STIRLING_PDF_ADMIN_PASSWORD
    remoteRef:
      key: STIRLING_PDF_ADMIN_PASSWORD
