---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
spec:
  chartRef:
    kind: OCIRepository
    name: stirling-pdf
  interval: 1h
  values:
    controllers:
      stirling-pdf:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stirling-tools/stirling-pdf
              tag: 2.14.0@sha256:a6c5e627ceef6ed323a63da13e0d44ef68503320d1917cbc7ca2fd8e4a827aae
            envFrom:
            - secretRef:
                name: "{{ .Release.Name }}"
            env:
              TZ: America/Los_Angeles
              MODE: BOTH
              DOCKER_ENABLE_SECURITY: "false"
              METRICS_ENABLED: "false"
              SYSTEM_ENABLEANALYTICS: "false"
              SYSTEM_GOOGLEVISIBILITY: "false"
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 4Gi
    service:
      app:
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames:
        - "pdf.brenix.com"
        parentRefs:
        - name: envoy-internal
          namespace: network
    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
        - path: /logs
          subPath: logs
        - path: /pipeline
          subPath: pipeline
        - path: /tmp
          subPath: tmp
