---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
- ../../components/alerts
resources:
- ./namespace.yaml
- ./jellyfin/ks.yaml
- ./linkding/ks.yaml
- ./mongodb/ks.yaml
- ./prowlarr/ks.yaml
- ./radarr/ks.yaml
- ./recyclarr/ks.yaml
- ./sabnzbd/ks.yaml
- ./seerr/ks.yaml
- ./sonarr/ks.yaml
- ./stirling-pdf/ks.yaml
- ./unifi/ks.yaml
# - ./slskd/ks.yaml
# - ./mumble/ks.yaml
# - ./navidrome/ks.yaml
# - ./pacoloco/ks.yaml
