---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: gitea-admin
    template:
      data:
        username: "{{ .GITEA_USER }}"
        password: "{{ .GITEA_PASS }}"
        email: "{{ .GITEA_EMAIL }}"
  data:
  - secretKey: &userKey GITEA_USER
    remoteRef:
      key: *userKey
  - secretKey: &passKey GITEA_PASS
    remoteRef:
      key: *passKey
  - secretKey: &emailKey GITEA_EMAIL
    remoteRef:
      key: *emailKey

