---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./ocirepository.yaml
- ./helmrelease.yaml
- ./pvc-data.yaml
- ./externalsecret.yaml
configMapGenerator:
- name: forgejo-customizations
  files:
  - custom.css=./resources/custom.css
  - header.tmpl=./resources/header.tmpl
generatorOptions:
  disableNameSuffixhash: true
