---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ocharted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: ocharted-secret
    template:
      data:
        auth: "{{ .OCHARTED_USERNAME }}:{{ .OCHARTED_PASSWORD }}"
  data:
  - secretKey: &userKey OCHARTED_USERNAME
    remoteRef:
      key: *userKey
  - secretKey: &passKey OCHARTED_PASSWORD
    remoteRef:
      key: *passKey
