---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ping-exporter
spec:
  interval: 15m
  url: https://raw.githubusercontent.com/czerwonk/ping_exporter/main/dist/charts

