---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lidarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: lidarr
    template:
      data:
        LIDARR__AUTH__APIKEY: "{{ .LIDARR_API_KEY }}"
  data:
  - secretKey: &key LIDARR_API_KEY
    remoteRef:
      key: *key
