---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: cloudflare
    template:
      data:
        api-token: "{{ .CLOUDFLARE_API_KEY }}"
  data:
  - secretKey: &key CLOUDFLARE_API_KEY
    remoteRef:
      key: *key
