---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.50:6443
additionalApiServerCertSans: &sans
- "127.0.0.1"
- "192.168.1.50"
- "k8s.home.arpa"
additionalMachineCertSans: *sans

clusterPodNets:
- "10.244.0.0/16"
clusterSvcNets:
- "10.96.0.0/16"

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
- hostname: "k01"
  ipAddress: "192.168.1.51"
  installDiskSelector:
    serial: "CT500P3PSSD8"
  machineSpec:
    secureboot: false
  talosImageURL: factory.talos.dev/installer/7545b3eddee40c81816011818d49ad819ccd3ff1f489422572a1f9831ca2eb98
  controlPlane: true
  networkInterfaces:
  - deviceSelector:
      hardwareAddr: "e8:ff:1e:d7:c7:7d"
    dhcp: false
    addresses:
    - "192.168.1.51/24"
    routes:
    - network: "0.0.0.0/0"
      gateway: "192.168.1.1"
    mtu: 1420
    vip:
      ip: "192.168.1.50"
- hostname: "k02"
  ipAddress: "192.168.1.52"
  installDiskSelector:
    serial: "CT500P3PSSD8"
  machineSpec:
    secureboot: false
  talosImageURL: factory.talos.dev/installer/7545b3eddee40c81816011818d49ad819ccd3ff1f489422572a1f9831ca2eb98
  controlPlane: true
  networkInterfaces:
  - deviceSelector:
      hardwareAddr: "e8:ff:1e:d7:c7:f9"
    dhcp: false
    addresses:
    - "192.168.1.52/24"
    routes:
    - network: "0.0.0.0/0"
      gateway: "192.168.1.1"
    mtu: 1420
    vip:
      ip: "192.168.1.50"
- hostname: "k03"
  ipAddress: "192.168.1.53"
  installDiskSelector:
    serial: "CT500P3PSSD8"
  machineSpec:
    secureboot: false
  talosImageURL: factory.talos.dev/installer/7545b3eddee40c81816011818d49ad819ccd3ff1f489422572a1f9831ca2eb98
  controlPlane: true
  networkInterfaces:
  - deviceSelector:
      hardwareAddr: "e8:ff:1e:d7:c7:6f"
    dhcp: false
    addresses:
    - "192.168.1.53/24"
    routes:
    - network: "0.0.0.0/0"
      gateway: "192.168.1.1"
    mtu: 1420
    vip:
      ip: "192.168.1.50"

# Global patches
patches:
- "@./patches/global/machine-features.yaml"
- "@./patches/global/machine-files.yaml"
- "@./patches/global/machine-kubelet.yaml"
- "@./patches/global/machine-network.yaml"
- "@./patches/global/machine-sysctls.yaml"
- "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
  - "@./patches/controller/cluster.yaml"

