---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mumble
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: mumble
    template:
      data:
        MUMBLE_SUPERUSER_PASSWORD: "{{ .MUMBLE_SUPERUSER_PASSWORD }}"
  data:
  - secretKey: &key MUMBLE_SUPERUSER_PASSWORD
    remoteRef:
      key: *key
