---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: sonarr
    template:
      data:
        SONARR__AUTH__APIKEY: "{{ .SONARR_API_KEY }}"
  data:
  - secretKey: &key SONARR_API_KEY
    remoteRef:
      key: *key
