---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
spec:
  chartRef:
    kind: OCIRepository
    name: mongodb
  interval: 1h
  values:
    controllers:
      mongodb:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/library/mongo
              tag: 8.2.3@sha256:dfa32f68d02281185978619aac453896c85c46ee4911c93b8e5a5d2167af4856
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 1Gi
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
        type: statefulset
    service:
      app:
        ports:
          mongodb:
            enabled: true
            port: 27017
            primary: true
            protocol: TCP
        type: ClusterIP
    persistence:
      data:
        enabled: true
        existingClaim: "mongo-data"
        globalMounts:
        - path: /data/db
      initdb:
        enabled: true
        globalMounts:
        - path: /docker-entrypoint-initdb.d
        name: mongodb-init
        type: secret
