---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: brenix.com-tls
spec:
  secretStoreRefs:
  - name: doppler
    kind: ClusterSecretStore
  selector:
    secret:
      name: brenix.com-tls
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
  - match:
      secretKey: &key tls.crt
      remoteRef:
        remoteKey: BRENIX_COM_CRT
        property: *key
  - match:
      secretKey: &key tls.key
      remoteRef:
        remoteKey: BRENIX_COM_KEY
        property: *key
