---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-init
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: forgejo-runner-init
    template:
      data:
        CONFIG_INSTANCE: https://git.brenix.com
        CONFIG_NAME: home-ops
        CONFIG_TOKEN: "{{ .FORGEJO_RUNNER_TOKEN }}"
  data:
  - secretKey: &token FORGEJO_RUNNER_TOKEN
    remoteRef:
      key: *token
